//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int Id { get; set; }
        public string Content { get; set; }
        public string Contact { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Dictionary DictionaryStatus { get; set; }
    }
}
