//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Services
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Services()
        {
            this.WorkersServices = new HashSet<WorkersServices>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Hours { get; set; }
        public System.DateTime DateAdd { get; set; }
        public Nullable<System.DateTime> DateFinish { get; set; }
        public Nullable<decimal> CostSum { get; set; }
        public string Description { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Dictionary Dictionary { get; set; }
        public virtual Workers Workers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkersServices> WorkersServices { get; set; }
    }
}
