//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkersServices
    {
        public int Id { get; set; }
    
        public virtual Workers Workers { get; set; }
        public virtual Services Services { get; set; }
    }
}
